# Install Nginx software in server.
- name: Install Nginx
  yum:
    name: nginx
    state: present
# Configure the nginx.conf file  
- name: generate Nginx site config
  template:
      src: site.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0744
# Copy the html file to website root path
- name: Generate index.html
  template:
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0744


# Start Nginx web service 
- name: Enable Nginx service
  systemd:
    name: nginx
    daemon_reload: yes
    enabled: yes
    state: started
